name: Deploy Vue to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build || (echo "::error::Build failed! Check console output." && exit 1)
          echo "Build artifacts structure:"
          ls -R dist

      - name: Prepare deployment
        run: |
          # 确保目标目录存在
          mkdir -p dist/.well-known
          # 添加部署标记文件
          echo "Deployed at $(date)" > dist/deployment.txt

      - name: Deploy via SFTP
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "dist"
          remoteDir: ${{ secrets.SERVER_DESTINATION }}
          retry: 3
          retryWait: 5000
          ignoreHidden: false # 确保上传隐藏文件
          verify: true # 验证文件传输完整性

      - name: Post-deployment check
        run: |
          echo "Deployment completed at $(date -u)"
          echo "Live site URL: http://${{ secrets.SERVER_IP }}/"
