name: Deploy Vue to Server

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.js' # 或 vue.config.js 如果使用Vue CLI

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Verify build output
        run: |
          ls -la dist
          [ -f dist/index.html ] || exit 1
          
      - name: Deploy via SFTP (Password)
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "dist"
          remoteDir: ${{ secrets.SERVER_DESTINATION }}
          retry: 3 # 添加重试机制
