name: Deploy Vue to BT via Rsync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Rsync Deployment
        uses: burnett01/rsync-deployments@5.2.3
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.SERVER_DESTINATION }}
          remote_host: ${{ secrets.SERVER_IP }}
          remote_port: ${{ secrets.SERVER_PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}

      - name: Post-deploy cleanup
        run: echo "Deployed to ${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}"
