name: Deploy Vue to Server with Rsync (Password Auth)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          npm run build
          # 检查构建文件是否完整
          ls -lh dist/
          tail -n 5 dist/js/app.*.js

      - name: Install rsync and sshpass (用于密码认证)
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Deploy via Rsync (Password Auth)
        run: |
          # 使用 sshpass 传递密码
          export SSHPASS=${{ secrets.SSH_PASSWORD }}
          rsync -avzr --delete \
            --rsh="sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT || '22' }}" \
            ./dist/ \
            ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}

      - name: Verify deployment (可选)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_DESTINATION }}
            ls -lh js/
            tail -n 5 js/app.*.js
            echo "Deployment verification complete"
